"use client";
import { useState } from "react";
import { useToast } from "@/hooks/useToast";
import Toast from "@/components/ui/Toast";
import { isValidEmail } from "@/lib/utils";
import styles from "./ghp.module.css";
export default function GHPPage() {
  const { toastState, showToast } = useToast(); const [form, setForm] = useState({ name: "", email: "", contact: "", preferredDate: "", remarks: "" }); const [saving, setSaving] = useState(false); const [submitted, setSubmitted] = useState(false);
  const update = (field) => (e) => setForm((v) => ({ ...v, [field]: e.target.value }));
  async function submit(e) { e.preventDefault(); if (!form.name.trim() || !isValidEmail(form.email)) return showToast("Please enter your full name and a valid email address.", true); setSaving(true); try { const r = await fetch("/api/ghp/appointment", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const j = await r.json(); if (!r.ok || !j.success) throw new Error(j.error); setSubmitted(true); showToast("Your GHP seminar appointment request has been saved."); } catch (error) { showToast(error.message || "Unable to submit your appointment.", true); } finally { setSaving(false); } }
  return <><div className="page-hero"><div className="container"><h1>Good Hygienic Practice (GHP) Seminar</h1><p>Book your required GHP seminar appointment for MTV registration.</p></div></div><main className={styles.page}><div className="container"><section className={styles.overview}><div><span className={styles.kicker}>GHP Certification</span><h2>Attend the seminar and receive your certificate by email.</h2><p>Submit an appointment request below. NMIS will schedule your GHP seminar and email your confirmed date, time, and venue. Your certificate is issued after attendance is confirmed.</p></div><div className={styles.summaryGrid}><div><span>Step 1</span><strong>Request appointment</strong></div><div><span>Step 2</span><strong>Attend seminar</strong></div><div><span>Step 3</span><strong>Receive certificate</strong></div></div></section><section className={styles.reminders}><h2>Important Reminders</h2><ul><li>Use the name that should appear on your GHP certificate.</li><li>Watch your email for the confirmed seminar schedule.</li><li>Your certificate is issued only after attendance is confirmed by NMIS.</li></ul></section><section className={styles.appointmentCard}><h2>Request a GHP seminar appointment</h2>{submitted ? <div className={styles.success}>Your request has been received. NMIS will email your seminar schedule using the address you provided.</div> : <form className={styles.appointmentForm} onSubmit={submit}><label>Full name *<input value={form.name} onChange={update("name")} required placeholder="Name for your certificate" /></label><label>Email address *<input type="email" value={form.email} onChange={update("email")} required placeholder="you@email.com" /></label><label>Contact number<input value={form.contact} onChange={update("contact")} placeholder="Optional" /></label><label>Preferred seminar date<input type="date" value={form.preferredDate} onChange={update("preferredDate")} min={new Date().toISOString().slice(0, 10)} /></label><label className={styles.fullWidth}>Notes or preferred schedule<textarea value={form.remarks} onChange={update("remarks")} rows="3" placeholder="Optional" /></label><button className="btn btn-primary btn-lg" disabled={saving}>{saving ? "Saving appointment…" : "Request appointment"}</button></form>}</section></div></main><Toast {...toastState} /></>;
}
