"use client";
import { useEffect, useState } from "react";
import { useToast } from "@/hooks/useToast";
import Toast from "@/components/ui/Toast";
import { isValidEmail } from "@/lib/utils";
import styles from "./ghp.module.css";

const fmt = (value) => new Date(`${value}T00:00:00`).toLocaleDateString("en-PH", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
export default function GHPPage() {
  const { toastState, showToast } = useToast(); const [form, setForm] = useState({ name: "", email: "", contact: "", seminarDate: "", remarks: "" }); const [schedules, setSchedules] = useState([]); const [saving, setSaving] = useState(false); const [submitted, setSubmitted] = useState(false); const [loading, setLoading] = useState(true);
  const update = (field) => (e) => setForm((v) => ({ ...v, [field]: e.target.value }));
  async function loadSchedules() { setLoading(true); try { const r = await fetch("/api/ghp/appointment", { cache: "no-store" }); const j = await r.json(); if (!r.ok || !j.success) throw new Error(j.error); setSchedules(j.schedules); } catch (error) { showToast(error.message || "Unable to load seminar availability.", true); } finally { setLoading(false); } }
  useEffect(() => { loadSchedules(); }, []);
  async function submit(e) { e.preventDefault(); if (!form.name.trim() || !isValidEmail(form.email) || !form.seminarDate) return showToast("Please enter your full name, a valid email address, and select a seminar schedule.", true); setSaving(true); try { const r = await fetch("/api/ghp/appointment", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const j = await r.json(); if (!r.ok || !j.success) throw new Error(j.error); setSubmitted(true); showToast("Your GHP seminar booking has been saved."); } catch (error) { showToast(error.message || "Unable to submit your booking.", true); await loadSchedules(); } finally { setSaving(false); } }
  return <><div className="page-hero"><div className="container"><h1>Good Hygienic Practice (GHP) Seminar</h1><p>Choose an available GHP seminar schedule for MTV registration.</p></div></div><main className={styles.page}><div className="container"><section className={styles.overview}><div><span className={styles.kicker}>GHP Certification</span><h2>Book your seminar, then await your examination result.</h2><p>Seminars are held on the displayed dates and each schedule has a maximum of 30 participants. Examination results are recorded by NMIS and sent to your email.</p></div><div className={styles.summaryGrid}><div><span>Step 1</span><strong>Choose a schedule</strong></div><div><span>Step 2</span><strong>Attend the seminar</strong></div><div><span>Step 3</span><strong>Receive your result</strong></div></div></section><section className={styles.reminders}><h2>Important Reminders</h2><ul><li>Use the name that should appear on your certificate.</li><li>Schedules are first-come, first-served and close at 30 bookings.</li><li>Certificates are printed and signed manually by NMIS after a passing result.</li></ul></section><section className={styles.appointmentCard}><h2>Book a GHP seminar schedule</h2>{submitted ? <div className={styles.success}>Your booking has been received for <strong>{fmt(form.seminarDate)}</strong>. Please attend on time. NMIS will email your examination result after it is manually recorded.</div> : <form className={styles.appointmentForm} onSubmit={submit}><label>Full name *<input value={form.name} onChange={update("name")} required placeholder="Name for your certificate" /></label><label>Email address *<input type="email" value={form.email} onChange={update("email")} required placeholder="you@email.com" /></label><label>Contact number<input value={form.contact} onChange={update("contact")} placeholder="Optional" /></label><fieldset className={styles.schedulePicker}><legend>Available seminar schedule *</legend>{loading ? <p>Loading available schedules…</p> : schedules.map((schedule) => <label key={schedule.date} className={schedule.available ? styles.schedule : styles.scheduleFull}><input type="radio" name="seminarDate" value={schedule.date} checked={form.seminarDate === schedule.date} onChange={update("seminarDate")} disabled={!schedule.available} /><span><strong>{fmt(schedule.date)}</strong><small>{schedule.available ? `${schedule.available} of ${schedule.capacity} seats available` : "Full"}</small></span></label>)}</fieldset><label className={styles.fullWidth}>Notes<textarea value={form.remarks} onChange={update("remarks")} rows="3" placeholder="Optional" /></label><button className="btn btn-primary btn-lg" disabled={saving || loading}>{saving ? "Saving booking…" : "Book seminar schedule"}</button></form>}</section></div></main><Toast {...toastState} /></>;
}
