"use client";
/**
 * components/ghp/CertCard.jsx
 *
 * Step 3 of the GHP flow.
 * - Collects name + email from the user
 * - Calls POST /api/ghp to validate score server-side and send certificate email
 * - Shows that the certificate has been queued for Apps Script processing
 */

import { useState } from "react";
import { isValidEmail } from "@/lib/utils";
import styles from "./CertCard.module.css";

export default function CertCard({
  unlocked,
  quizScore,
  quizTotal = 10,
  showToast,
}) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [sending, setSending] = useState(false);
  const [queued, setQueued] = useState(null); // { submittedAt }

  async function handleClaim() {
    if (!name.trim()) {
      showToast("Please enter your full name.", true);
      return;
    }
    if (!email.trim()) {
      showToast("Please enter your email address.", true);
      return;
    }
    if (!isValidEmail(email)) {
      showToast("Please enter a valid email address.", true);
      return;
    }

    setSending(true);
    try {
      const res = await fetch("/api/ghp", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: name.trim(),
          email: email.trim(),
          score: quizScore,
        }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error);
      setQueued({ submittedAt: json.submittedAt });
      showToast("✅ Certificate queued. Please check your email shortly.");
    } catch (err) {
      showToast(
        err.message || "Failed to send certificate. Please try again.",
        true,
      );
    } finally {
      setSending(false);
    }
  }

  const scorePct =
    quizTotal > 0 ? Math.round((quizScore / quizTotal) * 100) : 0;

  return (
    <div className={styles.card}>
      {/* ── Header ── */}
      <div className={styles.header}>
        <div className={styles.headerIcon}>🎓</div>
        <div className={styles.headerText}>
          <h3>Step 3 – Claim Your GHP Certificate</h3>
          <p>Enter your details to receive the certificate via email</p>
        </div>
        <span
          className={`tag ${!unlocked ? "tag-locked" : queued ? "tag-active" : "tag-pending"}`}
          style={{ marginLeft: "auto", flexShrink: 0 }}>
          {!unlocked ? "🔒 Locked" : queued ? "✅ Queued" : "📧 Pending"}
        </span>
      </div>

      <div className={styles.body}>
        {/* ── Locked state ── */}
        {!unlocked && (
          <div className={styles.lockedMsg}>
            🔒&nbsp; Pass the qualification quiz above to unlock your
            certificate.
          </div>
        )}

        {/* ── Certificate queued ── */}
        {unlocked && queued && (
          <div className={styles.successBox}>
            <div className={styles.successIcon}>🎉</div>
            <h4>Certificate Queued!</h4>
            <p>
              Your GHP Certificate of Completion will be sent to{" "}
              <strong>{email}</strong>.
            </p>
            <p style={{ fontSize: ".85rem", color: "var(--gray-500)" }}>
              Please check your inbox and spam folder once the certificate is
              processed.
            </p>

            {/* Certificate details */}
            <div className={styles.certDetails}>
              <div className={styles.certRow}>
                <span>Submitted</span>
                <strong>{queued.submittedAt}</strong>
              </div>
              <div className={styles.certRow}>
                <span>Quiz Score</span>
                <strong>
                  {quizScore}/{quizTotal}&nbsp;({scorePct}%)
                </strong>
              </div>
            </div>

            <div className={styles.infoNote}>
              📋 Your control number will be generated by NMIS and included in
              the emailed certificate. Use that number when submitting an MTV
              accreditation application on the{" "}
              <a
                href="/apply"
                style={{ color: "var(--green)", fontWeight: 700 }}>
                MTV Application
              </a>{" "}
              page.
            </div>
          </div>
        )}

        {/* ── Claim form ── */}
        {unlocked && !queued && (
          <>
            <p className={styles.intro}>
              Congratulations on passing the GHP quiz! Enter your full name and
              email address to receive your official{" "}
              <strong>Certificate of Completion</strong>.
            </p>

            {/* Score preview */}
            <div className={styles.scorePreview}>
              <span>🏆</span>
              <span>
                Your score:&nbsp;
                <strong>
                  {quizScore}/{quizTotal}
                </strong>
                &nbsp;·&nbsp;
                <strong>{scorePct}%</strong>
                &nbsp;— Pass ✅
              </span>
            </div>

            {/* Name field */}
            <div className={styles.formGroup}>
              <label htmlFor="cert_name">
                Full Name <span style={{ color: "var(--red)" }}>*</span>
              </label>
              <input
                id="cert_name"
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. Juan Santos dela Cruz"
                disabled={sending}
              />
              <span className={styles.hint}>
                This name will appear on your certificate exactly as typed.
              </span>
            </div>

            {/* Email field */}
            <div className={styles.formGroup}>
              <label htmlFor="cert_email">
                Email Address <span style={{ color: "var(--red)" }}>*</span>
              </label>
              <input
                id="cert_email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="your@email.com"
                disabled={sending}
              />
              <span className={styles.hint}>
                The certificate will be sent here. Check your spam folder if you
                don't see it within 5 minutes.
              </span>
            </div>

            {/* Live certificate preview */}
            <div className={styles.certPreview}>
              <div className={styles.ribbonTop} />
              <div className={styles.certPreviewBody}>
                <div className={styles.certAgency}>
                  <img src="/nmis-logo.svg" alt="" />
                  <div>
                    <p>Republic of the Philippines</p>
                    <p>Department of Agriculture</p>
                    <strong>National Meat Inspection Service</strong>
                    <p>Region III, Regional Government Center</p>
                    <p>Maimpis, San Fernando, Pampanga 2000</p>
                    <p>Telefax No. (045) 4554532</p>
                  </div>
                </div>

                <h4>Certificate of Completion</h4>
                <p className={styles.givenText}>is hereby given to</p>

                <div className={styles.certMain}>
                  <div className={styles.certCopy}>
                    <strong className={styles.certName}>
                      {name.trim() || "Your Name Here"}
                    </strong>
                    <p>
                      for having satisfactorily participated in the
                      <br />
                      <b>
                        MTV Drivers and Pahinante Good Hygienic Practices (GHP)
                        Orientation
                      </b>
                      <br />
                      on{" "}
                      <b>
                        {new Date().toLocaleDateString("en-PH", {
                          year: "numeric",
                          month: "long",
                          day: "2-digit",
                        })}
                      </b>{" "}
                      via Virtual Orientation.
                    </p>

                    <p className={styles.validityText}>
                      This is a pre-requisite requirement for MTV Registration
                      Application and shall be valid until{" "}
                      <b>
                        {new Date(
                          new Date().setFullYear(new Date().getFullYear() + 1),
                        ).toLocaleDateString("en-PH", {
                          year: "numeric",
                          month: "long",
                          day: "2-digit",
                        })}
                      </b>
                    </p>
                  </div>

                  <div className={styles.qrBlock}>
                    <div className={styles.qrMock}>QR Code</div>
                    <p>Scan to Verify</p>
                  </div>
                </div>

                <div className={styles.certFooter}>
                  <div className={styles.signatureBlock}>
                    <strong>MA. THERESA D. MAGDARAOOG, DVM, MPMRD</strong>
                    <p>
                      Supervising Meat Control Officer, Designated Admin Officer
                    </p>
                  </div>

                  <div className={styles.controlBlock}>
                    <strong>GHP-{new Date().getFullYear()}-1001</strong>
                    <p>"Safe Meat For All"</p>
                    <span>NMIS is ISO 9001:2015 Certified</span>
                  </div>
                </div>
              </div>
              <div className={styles.ribbonBottom} />
            </div>

            {/* Send button */}
            <div className={styles.actions}>
              <button
                className="btn btn-primary btn-lg"
                onClick={handleClaim}
                disabled={sending}>
                {sending
                  ? "⏳ Sending Certificate…"
                  : "📧 Send Certificate to My Email"}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
