"use client";
import { useEffect, useMemo, useState } from "react";
import styles from "./GHPAppointments.module.css";

const fmt = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-PH", { weekday: "long", year: "numeric", month: "short", day: "numeric" }) : "Unscheduled";
export default function GHPAppointments() {
  const [items, setItems] = useState([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const batches = useMemo(() => Object.entries(items.reduce((groups, item) => { const date = item.seminar_date || ""; (groups[date] ||= []).push(item); return groups; }, {})).sort(([a], [b]) => a.localeCompare(b)), [items]);
  async function load() { const response = await fetch("/api/admin/ghp", { cache: "no-store" }); const data = await response.json(); if (response.ok && data.success) setItems(data.appointments); else setMessage(data.error || "Unable to load GHP bookings."); }
  useEffect(() => { load(); }, []);
  async function syncResults() { setBusy(true); setMessage(""); try { const response = await fetch("/api/admin/ghp", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "sync-manual-results" }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error); setMessage([data.message, ...(data.errors || [])].join(" ")); await load(); } catch (error) { setMessage(error.message || "Result sync failed."); } finally { setBusy(false); } }
  return <section className={styles.section}><div className={styles.heading}><div><span>GHP Certification</span><h2>Seminar attendee batches</h2><p>The date selected by each client is final. Attendees are grouped by their booked seminar schedule.</p></div><div className={styles.actions}><button onClick={load}>Refresh</button><button className={styles.primary} onClick={syncResults} disabled={busy}>{busy ? "Sending…" : "Send manual result emails"}</button></div></div>{message && <div className={styles.message}>{message}</div>}{batches.length ? <div className={styles.batches}>{batches.map(([date, attendees]) => <section className={styles.batch} key={date || "unscheduled"}><div className={styles.batchHeader}><div><span>Seminar batch</span><h3>{fmt(date)}</h3></div><strong>{attendees.length} / 30 attendees</strong></div><div className={styles.tableWrap}><table className={styles.attendeeTable}><thead><tr><th>Client</th><th>Contact</th><th>Booking ID</th><th>Exam result</th><th>Certificate</th></tr></thead><tbody>{attendees.map((item) => <tr key={item.appointment_id}><td data-label="Client"><strong>{item.name}</strong><span>{item.email}</span></td><td data-label="Contact">{item.contact || "—"}</td><td data-label="Booking ID"><code>{item.appointment_id}</code></td><td data-label="Exam result">{item.exam_result || "Awaiting manual entry"}</td><td data-label="Certificate">{item.exam_result === "PASSED" && item.certificate_number ? <a href={`/api/admin/ghp/certificate?appointmentId=${encodeURIComponent(item.appointment_id)}`} target="_blank" rel="noreferrer">Print</a> : "—"}</td></tr>)}</tbody></table></div></section>)}</div> : <div className={styles.empty}>No GHP seminar bookings yet.</div>}</section>;
}
