"use client";
import { useEffect, useState } from "react";
import styles from "./GHPAppointments.module.css";

const fmt = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-PH", { year: "numeric", month: "short", day: "numeric" }) : "—";
export default function GHPAppointments() {
  const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [form, setForm] = useState({ seminarDate: "", seminarTime: "", seminarVenue: "", meetingLink: "", certificateNumber: "" }); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function load() { const r = await fetch("/api/admin/ghp", { cache: "no-store" }); const j = await r.json(); if (r.ok && j.success) setItems(j.appointments); else setMessage(j.error || "Unable to load GHP appointments."); }
  useEffect(() => { load(); }, []);
  function choose(item) { setSelected(item); setForm({ seminarDate: item.seminar_date || "", seminarTime: item.seminar_time || "", seminarVenue: item.seminar_venue || "", meetingLink: item.meeting_link || "", certificateNumber: item.certificate_number || "" }); setMessage(""); }
  const update = (name) => (e) => setForm((f) => ({ ...f, [name]: e.target.value }));
  async function action(action) { if (!selected) return; setBusy(true); setMessage(""); try { const r = await fetch("/api/admin/ghp", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, appointmentId: selected.appointment_id, ...form }) }); const j = await r.json(); if (!r.ok || !j.success) throw new Error(j.error); setMessage(j.message); setSelected(j.appointment); choose(j.appointment); await load(); } catch (e) { setMessage(e.message || "Action failed."); } finally { setBusy(false); } }
  return <section className={styles.section}><div className={styles.heading}><div><span>GHP Certification</span><h2>Seminar appointments</h2><p>Schedule the seminar, notify the client, and issue certificates after attendance.</p></div><button onClick={load}>Refresh</button></div>{message && <div className={styles.message}>{message}</div>}<div className={styles.layout}><div className={styles.list}>{items.length ? items.map((item) => <button key={item.appointment_id} className={selected?.appointment_id === item.appointment_id ? styles.selected : styles.item} onClick={() => choose(item)}><strong>{item.name}</strong><span>{item.email}</span><small>{item.status || "Pending"} · Requested {fmt(item.requested_at?.slice(0, 10))}</small></button>) : <p>No GHP appointments yet.</p>}</div><div className={styles.detail}>{selected ? <><h3>{selected.name}</h3><p>{selected.email} {selected.contact ? `· ${selected.contact}` : ""}</p><p><b>Preferred date:</b> {fmt(selected.preferred_date)}<br /><b>Notes:</b> {selected.remarks || "—"}</p><div className={styles.form}><label>Seminar date<input type="date" value={form.seminarDate} onChange={update("seminarDate")} /></label><label>Seminar time<input value={form.seminarTime} onChange={update("seminarTime")} placeholder="e.g. 9:00 AM" /></label><label>Venue<input value={form.seminarVenue} onChange={update("seminarVenue")} placeholder="NMIS RTOC III" /></label><label>Online meeting link<input value={form.meetingLink} onChange={update("meetingLink")} placeholder="Optional" /></label></div><button className={styles.primary} onClick={() => action("schedule")} disabled={busy}>{busy ? "Saving…" : "Save schedule & email client"}</button><hr /><label className={styles.certificate}>Certificate number<input value={form.certificateNumber} onChange={update("certificateNumber")} placeholder="Auto-generated if blank" /></label><div className={styles.actions}><button className={styles.primary} onClick={() => action("issue-certificate")} disabled={busy}>{busy ? "Generating…" : "Generate & email certificate"}</button>{selected.certificate_number && <a href={`/api/admin/ghp/certificate?appointmentId=${encodeURIComponent(selected.appointment_id)}`} target="_blank" rel="noreferrer">Print certificate</a>}</div></> : <p>Select an appointment to schedule its seminar or issue a certificate.</p>}</div></div></section>;
}
