"use client";
import { useEffect, useMemo, useState } from "react";
import styles from "./GHPAppointments.module.css";

const fmt = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-PH", { weekday: "long", year: "numeric", month: "short", day: "numeric" }) : "Unscheduled";

export default function GHPAppointments() {
  const [items, setItems] = useState([]); const [selectedDate, setSelectedDate] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [drafts, setDrafts] = useState({}); const [savingId, setSavingId] = useState("");
  const dates = useMemo(() => [...new Set(items.map((item) => item.seminar_date || ""))].sort(), [items]);
  const attendees = useMemo(() => items.filter((item) => item.seminar_date === selectedDate), [items, selectedDate]);
  async function load() { const response = await fetch("/api/admin/ghp", { cache: "no-store" }); const data = await response.json(); if (response.ok && data.success) { setItems(data.appointments); setSelectedDate((current) => current && data.appointments.some((item) => item.seminar_date === current) ? current : [...new Set(data.appointments.map((item) => item.seminar_date || ""))].sort()[0] || ""); } else setMessage(data.error || "Unable to load GHP bookings."); }
  useEffect(() => { load(); }, []);
  const changeDraft = (id, field, value) => setDrafts((current) => ({ ...current, [id]: { ...(current[id] || {}), [field]: value } }));
  async function saveResult(item) { const draft = drafts[item.appointment_id] || {}; if (!draft.score || !draft.result) { setMessage("Enter a score and select Passed or Failed before saving."); return; } setSavingId(item.appointment_id); setMessage(""); try { const response = await fetch("/api/admin/ghp", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ appointmentId: item.appointment_id, score: draft.score, result: draft.result }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error); setMessage(`Exam result saved for ${item.name}.`); setItems((current) => current.map((record) => record.appointment_id === item.appointment_id ? { ...record, exam_score: draft.score, exam_result: draft.result } : record)); } catch (error) { setMessage(error.message || "Unable to save the exam result."); } finally { setSavingId(""); } }
  async function syncResults() { setBusy(true); setMessage(""); try { const response = await fetch("/api/admin/ghp", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "sync-manual-results" }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error); setMessage([data.message, ...(data.errors || [])].join(" ")); await load(); } catch (error) { setMessage(error.message || "Result sync failed."); } finally { setBusy(false); } }
  return <section className={styles.section}><div className={styles.heading}><div><span>GHP Certification</span><h2>Seminar attendees and exam results</h2><p>Select a seminar date, then record each attendee’s score. Results are saved directly to the <strong>Manual Entries</strong> sheet tab.</p></div><div className={styles.actions}><button onClick={load}>Refresh</button><button className={styles.primary} onClick={syncResults} disabled={busy}>{busy ? "Sending…" : "Send result emails"}</button></div></div>{message && <div className={styles.message}>{message}</div>}{dates.length ? <><label className={styles.dateSelect}>Seminar date<select value={selectedDate} onChange={(event) => setSelectedDate(event.target.value)}>{dates.map((date) => <option value={date} key={date}>{fmt(date)}</option>)}</select></label><div className={styles.batch}><div className={styles.batchHeader}><div><span>Selected seminar</span><h3>{fmt(selectedDate)}</h3></div><strong>{attendees.length} attendee{attendees.length === 1 ? "" : "s"}</strong></div><div className={styles.tableWrap}><table className={styles.attendeeTable}><thead><tr><th>Client</th><th>Contact</th><th>Session</th><th>Exam score</th><th>Result</th><th>Action</th></tr></thead><tbody>{attendees.map((item) => { const draft = drafts[item.appointment_id] || {}; return <tr key={item.appointment_id}><td data-label="Client"><strong>{item.name}</strong><span>{item.email}</span></td><td data-label="Contact">{item.contact || "—"}</td><td data-label="Session">{item.seminar_time || "—"}</td><td data-label="Exam score"><input className={styles.scoreInput} value={draft.score ?? item.exam_score ?? ""} onChange={(event) => changeDraft(item.appointment_id, "score", event.target.value)} placeholder="e.g. 9/10" /></td><td data-label="Result"><select className={styles.resultSelect} value={draft.result ?? item.exam_result ?? ""} onChange={(event) => changeDraft(item.appointment_id, "result", event.target.value)}><option value="">Select</option><option value="PASSED">Passed</option><option value="FAILED">Failed</option></select></td><td data-label="Action"><button className={styles.saveButton} onClick={() => saveResult(item)} disabled={savingId === item.appointment_id}>{savingId === item.appointment_id ? "Saving…" : "Save result"}</button></td></tr>; })}</tbody></table></div></div></> : <div className={styles.empty}>No GHP seminar bookings yet.</div>}</section>;
}
